2020-05-03 23:01:55.387: ERROR: Traceback (most recent call last):
2020-05-03 23:01:55.387: ERROR:   File "python\gui\battlehits\utils.py", line 18, in <lambda>
2020-05-03 23:01:55.387: ERROR:   File "python\gui\battlehits\hooks.py", line 109, in handleKeyEvent
2020-05-03 23:01:55.387: ERROR:   File "mod_extended_auto_bl.py", line 272, in new_handler
2020-05-03 23:01:55.387: ERROR: TypeError: PlayerAvatar() Cannot directly construct objects of this type
